/**
 * Advisor で query_metric から呼べる指標の事前定義カタログ
 *
 * MetricDefinitions.tsx と同期するのが理想だが、UI 用と SQL 用は構造が異なるため、
 * SQL 実行可能な指標のみここで定義する。
 *
 * 新しい指標を追加する場合:
 * 1. METRIC_CATALOG に新しいエントリを追加
 * 2. queryMetricImpl にケースを追加
 * 3. MetricDefinitions.tsx にも UI 用定義を追加
 */

export type MetricGroupBy = 'none' | 'day' | 'lp_id' | 'campaign_code';

export interface MetricCatalogEntry {
  key: string;
  label: string;
  description: string;
  unit: string;
  /** 取得可能か (false の場合は reason / planned が必要) */
  available: boolean;
  reason?: string;
  plannedFrom?: string;
  /** 計算ロジックの説明 (LLM 向け) */
  calculation: string;
  /** 対応する group_by の種別 */
  supportedGroupBy: MetricGroupBy[];
}

export const METRIC_CATALOG: MetricCatalogEntry[] = [
  {
    key: 'TOTAL_WORKERS',
    label: '登録ワーカー数',
    description: '現在登録されているワーカーの総数 (退会者除外)',
    unit: '人',
    available: true,
    calculation: 'User テーブルで deleted_at IS NULL のレコード数',
    supportedGroupBy: ['none'],
  },
  {
    key: 'NEW_WORKERS',
    label: '入会ワーカー数',
    description: '期間内に新規登録したワーカー数',
    unit: '人',
    available: true,
    calculation: 'User の created_at が指定期間内のレコード数',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'TOTAL_FACILITIES',
    label: '登録施設数',
    description: '現在登録されている施設の総数 (退会除外)',
    unit: '件',
    available: true,
    calculation: 'Facility テーブルで deleted_at IS NULL のレコード数',
    supportedGroupBy: ['none'],
  },
  {
    key: 'TOTAL_JOBS',
    label: '求人総数',
    description: 'Job テーブルの全件数',
    unit: '件',
    available: true,
    calculation: 'Job テーブル全件',
    supportedGroupBy: ['none'],
  },
  {
    key: 'ACTIVE_JOBS',
    label: 'アクティブ求人数',
    description: '現在公開中の求人数',
    unit: '件',
    available: true,
    calculation: 'Job.status = "active" のレコード数',
    supportedGroupBy: ['none'],
  },
  {
    key: 'NEW_APPLICATIONS',
    label: '応募数',
    description: '期間内の応募件数',
    unit: '件',
    available: true,
    calculation: 'Application の created_at が指定期間内のレコード数',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'LP_PV',
    label: 'LP閲覧数',
    description: 'LP のページビュー数 (期間内)',
    unit: 'PV',
    available: true,
    calculation: 'LpPageView の created_at が指定期間内のレコード数',
    supportedGroupBy: ['none', 'day', 'lp_id', 'campaign_code'],
  },
  {
    key: 'LP_REGISTRATIONS',
    label: 'LP経由の登録数',
    description: '期間内の LP 経由のワーカー登録数',
    unit: '人',
    available: true,
    calculation: 'User の registration_lp_id が NOT NULL かつ created_at が指定期間内',
    supportedGroupBy: ['none', 'day', 'lp_id', 'campaign_code'],
  },
  {
    key: 'PUBLIC_JOB_PV',
    label: '公開求人詳細PV',
    description: '未ログイン状態での求人詳細閲覧数',
    unit: 'PV',
    available: true,
    calculation: 'PublicJobPageView の created_at が指定期間内',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'JOB_SEARCH_PV',
    label: 'ワーカーTOP訪問数',
    description: 'ログイン後のワーカーTOPページ閲覧数',
    unit: 'PV',
    available: true,
    calculation: 'JobSearchPageView の created_at が指定期間内',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'APPLICATION_CLICK',
    label: '応募クリック数',
    description: '求人詳細での応募ボタンクリック数 (ログイン後)',
    unit: '件',
    available: true,
    calculation: 'ApplicationClickEvent の created_at が指定期間内',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'LP_TO_LINE_CONV',
    label: 'LP経由LINE誘導クリック数',
    description: 'LP 内の LINE 友だち追加ボタン (button_id が line_ で始まる) のクリック数',
    unit: '件',
    available: true,
    calculation:
      'LpClickEvent の created_at が指定期間内、かつ button_id が line_register / line_register_cta / line_register_hero のいずれか',
    supportedGroupBy: ['none', 'day', 'lp_id', 'campaign_code'],
  },
  {
    key: 'LP_TO_REGISTER_CONV',
    label: 'LP経由新規登録クリック数',
    description:
      'LP 内の新規登録ボタン (button_id が cta_register / register_ で始まる) のクリック数。LINE 経由ではなく直接登録フォームへ遷移するボタン',
    unit: '件',
    available: true,
    calculation:
      'LpClickEvent の created_at が指定期間内、かつ button_id が cta_register もしくは register_ で始まるレコード数',
    supportedGroupBy: ['none', 'day', 'lp_id', 'campaign_code'],
  },
  // ── ワーカー集計系 (analytics-actions.ts の getWorkerAnalyticsData から移植) ──
  {
    key: 'WITHDRAWN_WORKERS',
    label: '退会ワーカー数',
    description: '期間内に退会 (deleted_at セット) したワーカー数',
    unit: '人',
    available: true,
    calculation: 'User の deleted_at が指定期間内のレコード数',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'WITHDRAWAL_RATE',
    label: '退会率',
    description: '期間開始時の登録ワーカー数に対する期間内退会数の割合 (%)',
    unit: '%',
    available: true,
    calculation: '期間内退会数 / 期間開始前の累計登録数 × 100 (start_date 直前時点で created_at < start)',
    supportedGroupBy: ['none'],
  },
  {
    key: 'CANCEL_RATE',
    label: 'キャンセル率',
    description: '期間内の応募のうち、ワーカー側キャンセルされた割合 (%)',
    unit: '%',
    available: true,
    calculation: 'Application.cancelled_by="WORKER" の件数 / 期間内応募総数 × 100',
    supportedGroupBy: ['none'],
  },
  {
    key: 'LAST_MINUTE_CANCEL_RATE',
    label: '直前キャンセル率',
    description: '勤務開始 24h 以内のキャンセルが期間内応募に占める割合 (%)',
    unit: '%',
    available: true,
    calculation:
      'Application.cancelled_by="WORKER" AND (workDate.work_date - updated_at) が 0〜24h の件数 / 期間内応募総数 × 100',
    supportedGroupBy: ['none'],
  },
  {
    key: 'WORKER_REVIEW_COUNT',
    label: 'ワーカー受領レビュー数',
    description: '期間内に施設→ワーカーで投稿されたレビュー件数',
    unit: '件',
    available: true,
    calculation: 'Review.reviewer_type="FACILITY" かつ created_at が期間内',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'WORKER_REVIEW_AVG',
    label: 'ワーカー平均評価',
    description: '期間内の施設→ワーカーレビューの rating 平均 (1〜5)',
    unit: '点',
    available: true,
    calculation: 'Review.reviewer_type="FACILITY" の rating 平均',
    supportedGroupBy: ['none'],
  },
  // ── 施設集計系 ──
  {
    key: 'NEW_FACILITIES',
    label: '施設登録数',
    description: '期間内に新規登録された施設数',
    unit: '件',
    available: true,
    calculation: 'Facility の created_at が期間内 AND deleted_at IS NULL',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'WITHDRAWN_FACILITIES',
    label: '退会施設数',
    description: '期間内に退会した施設数',
    unit: '件',
    available: true,
    calculation: 'Facility の deleted_at が期間内',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'FACILITY_WITHDRAWAL_RATE',
    label: '施設退会率',
    description: '期間開始時の登録施設数に対する期間内退会数の割合 (%)',
    unit: '%',
    available: true,
    calculation: '期間内退会施設数 / 期間開始前の累計登録施設数 × 100',
    supportedGroupBy: ['none'],
  },
  {
    key: 'FACILITY_REVIEW_COUNT',
    label: '施設受領レビュー数',
    description: '期間内にワーカー→施設で投稿されたレビュー件数',
    unit: '件',
    available: true,
    calculation: 'Review.reviewer_type="WORKER" かつ created_at が期間内',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'FACILITY_REVIEW_AVG',
    label: '施設平均評価',
    description: '期間内のワーカー→施設レビューの rating 平均 (1〜5)',
    unit: '点',
    available: true,
    calculation: 'Review.reviewer_type="WORKER" の rating 平均',
    supportedGroupBy: ['none'],
  },
  // ── 求人・マッチング系 ──
  {
    key: 'CHILD_JOB_COUNT',
    label: '子求人数',
    description: '期間内に新規作成された子求人 (JobWorkDate) 数',
    unit: '件',
    available: true,
    calculation: 'JobWorkDate.created_at が期間内',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'TOTAL_SLOTS',
    label: '総応募枠数',
    description: '期間内に作成された子求人の recruitment_count 合計',
    unit: '枠',
    available: true,
    calculation: 'JobWorkDate.created_at が期間内のレコードの SUM(recruitment_count)',
    supportedGroupBy: ['none'],
  },
  {
    key: 'REMAINING_SLOTS',
    label: '残応募枠数',
    description: '期間内に作成された子求人の残枠合計 (recruitment_count - 確定済み)',
    unit: '枠',
    available: true,
    calculation:
      'JobWorkDate ごとに MAX(0, recruitment_count - status NOT IN [APPLIED, CANCELLED] の応募数) を SUM',
    supportedGroupBy: ['none'],
  },
  {
    key: 'LIMITED_JOB_COUNT',
    label: '限定求人数',
    description: '期間内に作成された限定求人数 (job_type が LIMITED_*)',
    unit: '件',
    available: true,
    calculation: 'Job.job_type が LIMITED_WORKED または LIMITED_FAVORITE で created_at が期間内',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'OFFER_JOB_COUNT',
    label: 'オファー求人数',
    description: '期間内に作成されたオファー求人数 (job_type=OFFER)',
    unit: '件',
    available: true,
    calculation: 'Job.job_type="OFFER" で created_at が期間内',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'OFFER_ACCEPTANCE_RATE',
    label: 'オファー承諾率',
    description: 'オファー求人に対するキャンセル以外応募の割合 (%)',
    unit: '%',
    available: true,
    calculation: 'job.job_type="OFFER" の Application で status!="CANCELLED" の件数 / OFFER 求人数 × 100',
    supportedGroupBy: ['none'],
  },
  {
    key: 'MATCHING_COUNT',
    label: 'マッチング数',
    description: '期間内のマッチング成立件数 (status が APPLIED/CANCELLED 以外)',
    unit: '件',
    available: true,
    calculation: 'Application.created_at が期間内 AND status NOT IN [APPLIED, CANCELLED]',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'AVG_MATCHING_HOURS',
    label: 'マッチング期間平均 (時間)',
    description: '応募作成 → マッチング確定までの平均時間 (Application.updated_at - job.created_at)',
    unit: '時間',
    available: true,
    calculation:
      'マッチング成立 Application について avg(updated_at - job.created_at) を時間単位で算出',
    supportedGroupBy: ['none'],
  },
  // ── LP 系 (lp-tracking/route.ts 由来) ──
  {
    key: 'LP_SESSIONS',
    label: 'LP ユニークセッション数',
    description: 'LP 閲覧のユニークセッション数 (lp_id × campaign_code 単位で session_id を distinct)',
    unit: 'セッション',
    available: true,
    calculation:
      'LpPageView の (lp_id, campaign_code, session_id) の組合せで一意化、(lp_id, campaign_code) 単位で session_id を distinct count',
    supportedGroupBy: ['none', 'lp_id', 'campaign_code'],
  },
  {
    key: 'LP_EVENTS',
    label: 'LP イベント数 (CTA クリック)',
    description: 'LP 内の CTA クリック総数 (lp_click_events 全件)',
    unit: '件',
    available: true,
    calculation: 'LpClickEvent.created_at が期間内のレコード数',
    supportedGroupBy: ['none', 'day', 'lp_id', 'campaign_code'],
  },
  {
    key: 'LP_EVENT_CTR',
    label: 'LP イベント CTR',
    description: 'LP イベント数 / セッション数 × 100 (%)',
    unit: '%',
    available: true,
    calculation: 'LP_EVENTS / LP_SESSIONS × 100',
    supportedGroupBy: ['none'],
  },
  {
    key: 'LP_REGISTRATION_RATE',
    label: 'LP 登録率',
    description: 'LP 登録数 / LP セッション数 × 100 (%)',
    unit: '%',
    available: true,
    calculation: 'LP_REGISTRATIONS / LP_SESSIONS × 100',
    supportedGroupBy: ['none'],
  },
  // ── Funnel (登録動線) 系 (funnel-analytics/route.ts 由来) ──
  // 「期間内に新規登録した user_id」を起点に、各ステップへの到達 UU を計算する。
  {
    key: 'REGISTRATION_PAGE_PV',
    label: '登録ページ PV',
    description: '/register/worker ページの総閲覧数',
    unit: 'PV',
    available: true,
    calculation: 'RegistrationPageView.created_at が期間内のレコード数',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'REGISTRATION_PAGE_UU',
    label: '登録ページ UU',
    description: '/register/worker ページのユニークセッション数',
    unit: 'UU',
    available: true,
    calculation: 'RegistrationPageView の session_id distinct count',
    supportedGroupBy: ['none'],
  },
  {
    key: 'FUNNEL_REGISTERED',
    label: '登録完了 UU',
    description: '期間内に新規登録したワーカー数 (= NEW_WORKERS と同義の Funnel 起点)',
    unit: '人',
    available: true,
    calculation: 'User の created_at が期間内のレコード数',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'FUNNEL_VERIFIED',
    label: 'メール認証完了 UU',
    description: '期間内登録ワーカーのうち、メール認証を完了した人数',
    unit: '人',
    available: true,
    calculation: 'User.email_verified=true かつ created_at が期間内のレコード数',
    supportedGroupBy: ['none'],
  },
  {
    key: 'FUNNEL_SEARCH_REACHED',
    label: '求人検索ページ到達 UU',
    description: '期間内登録ワーカーのうち、JobSearchPageView を 1 回以上見た人数',
    unit: '人',
    available: true,
    calculation:
      '期間内登録ユーザーの user_id で JobSearchPageView の user_id を distinct count',
    supportedGroupBy: ['none'],
  },
  {
    key: 'FUNNEL_JOB_VIEWED',
    label: '求人詳細閲覧 UU',
    description: '期間内登録ワーカーのうち、求人詳細を 1 回以上見た人数',
    unit: '人',
    available: true,
    calculation:
      '期間内登録ユーザーの user_id で JobDetailPageView の user_id を distinct count',
    supportedGroupBy: ['none'],
  },
  {
    key: 'FUNNEL_BOOKMARKED',
    label: 'お気に入り登録 UU',
    description: '期間内登録ワーカーのうち、求人をお気に入りした人数',
    unit: '人',
    available: true,
    calculation:
      '期間内登録ユーザーの user_id で Bookmark (type=FAVORITE かつ target_job_id IS NOT NULL) の user_id を distinct count',
    supportedGroupBy: ['none'],
  },
  {
    key: 'FUNNEL_APPLIED',
    label: '応募完了 UU',
    description: '期間内登録ワーカーのうち、応募を 1 件以上した人数',
    unit: '人',
    available: true,
    calculation:
      '期間内登録ユーザーの user_id で Application の user_id を distinct count',
    supportedGroupBy: ['none'],
  },
  {
    key: 'OVERALL_CONVERSION_RATE',
    label: '全体 CVR',
    description: '登録 → 応募完了の全体 CVR (応募完了 UU / 登録 UU × 100)',
    unit: '%',
    available: true,
    calculation: 'FUNNEL_APPLIED / FUNNEL_REGISTERED × 100',
    supportedGroupBy: ['none'],
  },
  // ── B群: 応募系メトリクス (funnel-analytics / analytics-actions から移植) ──
  {
    key: 'APPLICATION_CLICK_UU',
    label: '応募クリック UU',
    description: '期間内登録ワーカーで応募ボタンをクリックしたユニークユーザー数',
    unit: 'UU',
    available: true,
    calculation:
      '期間内登録ユーザーの user_id で ApplicationClickEvent.user_id を distinct count',
    supportedGroupBy: ['none'],
  },
  {
    key: 'APPLICATION_DAYS',
    label: '応募日数',
    description: '期間内の応募件数 (1 応募 = 1 勤務日)。NEW_APPLICATIONS と同義。',
    unit: '日',
    available: true,
    calculation: 'Application.created_at が期間内のレコード数',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'APPLICATION_CONVERSION_RATE',
    label: '応募率 (全体)',
    description: '求人詳細閲覧 UU に対する応募 UU の比率 (%)',
    unit: '%',
    available: true,
    calculation:
      '期間内応募 UU / 期間内 JobDetailPageView UU × 100。閲覧ユーザー = 応募ユーザーの母集団は職務閲覧 UU',
    supportedGroupBy: ['none'],
  },
  {
    key: 'APPLICATIONS_PER_WORKER',
    label: 'ワーカー1人あたり応募数',
    description: '期間内応募 / 期間内応募ユニークワーカー数',
    unit: '件/人',
    available: true,
    calculation: 'Application 期間内総数 / Application.user_id distinct 数',
    supportedGroupBy: ['none'],
  },
  {
    key: 'AVG_APPLICATION_DAYS',
    label: '平均応募日数',
    description: 'ワーカー 1 人あたりの平均応募日数 (APPLICATIONS_PER_WORKER と同義)',
    unit: '日/人',
    available: true,
    calculation: 'Application 期間内総数 / Application.user_id distinct 数',
    supportedGroupBy: ['none'],
  },
  {
    key: 'AVG_APPLICATION_MATCHING_HOURS',
    label: '応募〜マッチング平均時間',
    description: '応募作成 → マッチング確定 (status が APPLIED/CANCELLED 以外に変化) の平均時間',
    unit: '時間',
    available: true,
    calculation:
      'マッチング成立 Application で avg(updated_at - created_at) を時間単位で算出 (AVG_MATCHING_HOURS と分母が異なる、起点は応募作成)',
    supportedGroupBy: ['none'],
  },
  {
    key: 'AVG_REGISTRATION_TO_APPLICATION_DAYS',
    label: '登録〜初応募 平均日数',
    description: '期間内登録ワーカーが初応募までに要した平均日数',
    unit: '日',
    available: true,
    calculation:
      '期間内登録ユーザーの各 user_id で「最初の Application.created_at - User.created_at」を日数換算した平均',
    supportedGroupBy: ['none'],
  },
  {
    key: 'AVG_JOB_MATCHING_HOURS',
    label: '求人作成〜マッチング平均時間',
    description: '求人 (Job) 作成 → 各求人で最初のマッチング成立までの平均時間',
    unit: '時間',
    available: true,
    calculation:
      'マッチング成立 Application について「最初の Application.updated_at - Job.created_at」をジョブ単位で求めた平均 (時間)',
    supportedGroupBy: ['none'],
  },
  // ── B群: 登録〜認証 UU 時間 ──
  {
    key: 'AVG_REGISTRATION_TO_VERIFY_HOURS',
    label: '登録〜認証 平均時間',
    description: '期間内登録ユーザーがメール認証を完了するまでの平均時間',
    unit: '時間',
    available: true,
    calculation:
      '期間内登録ユーザーで email_verified=true のもの。avg(email_verified_at - created_at) を時間単位で',
    supportedGroupBy: ['none'],
  },
  // ── B群: 求人詳細 (jobAnalytics) 系メトリクス ──
  {
    key: 'JOB_DETAIL_PV',
    label: '求人詳細 PV',
    description: 'ログイン後の求人詳細閲覧 PV (期間内)',
    unit: 'PV',
    available: true,
    calculation: 'JobDetailPageView.created_at が期間内のレコード数',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'JOB_DETAIL_USERS',
    label: '求人詳細 閲覧 UU',
    description: '求人詳細をログイン状態で見たユニークワーカー数',
    unit: 'UU',
    available: true,
    calculation: 'JobDetailPageView の user_id distinct count',
    supportedGroupBy: ['none'],
  },
  {
    key: 'JOB_DETAIL_APPLICATION_COUNT',
    label: '求人詳細 応募数',
    description: '期間内の全応募件数 (jobAnalytics タブの応募数と同義)',
    unit: '件',
    available: true,
    calculation: 'Application.created_at が期間内のレコード数 (NEW_APPLICATIONS と同義)',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'JOB_DETAIL_APPLICATION_USERS',
    label: '求人詳細 応募 UU',
    description: '期間内に応募したユニークワーカー数',
    unit: 'UU',
    available: true,
    calculation: 'Application.user_id distinct count (期間内)',
    supportedGroupBy: ['none'],
  },
  {
    key: 'JOB_DETAIL_APPLICATION_RATE',
    label: '求人詳細 → 応募率',
    description: '求人詳細閲覧 UU に対する応募 UU の比率 (%)',
    unit: '%',
    available: true,
    calculation: 'JOB_DETAIL_APPLICATION_USERS / JOB_DETAIL_USERS × 100',
    supportedGroupBy: ['none'],
  },
  {
    key: 'JOB_DETAIL_AVG_APPLICATION_DAYS',
    label: '求人詳細 平均応募日数',
    description: '求人詳細応募 UU あたりの応募件数平均 (= 応募件数 / 応募UU)',
    unit: '日/人',
    available: true,
    calculation: 'JOB_DETAIL_APPLICATION_COUNT / JOB_DETAIL_APPLICATION_USERS',
    supportedGroupBy: ['none'],
  },
  // ── B群: Funnel 拡張系メトリクス ──
  {
    key: 'FUNNEL_JOB_VIEWED_PV',
    label: '求人詳細閲覧 PV (Funnel)',
    description: '期間内登録ワーカーによる JobDetailPageView の総 PV',
    unit: 'PV',
    available: true,
    calculation:
      '期間内登録ユーザーの user_id で JobDetailPageView の count (UU ではなく PV)',
    supportedGroupBy: ['none'],
  },
  {
    key: 'FUNNEL_SEARCH_PV',
    label: '求人検索 PV (Funnel)',
    description: '期間内登録ワーカーによる JobSearchPageView の総 PV',
    unit: 'PV',
    available: true,
    calculation: '期間内登録ユーザーの user_id で JobSearchPageView の count',
    supportedGroupBy: ['none'],
  },
  // ── B群: 求人構造系メトリクス (analytics-actions の getMatchingAnalyticsData/getFacilityAnalyticsData から) ──
  {
    key: 'PARENT_JOB_COUNT',
    label: '親求人数',
    description: '期間内に作成された PUBLISHED 状態の親求人数 (Job)',
    unit: '件',
    available: true,
    calculation: 'Job.created_at が期間内 AND status="PUBLISHED" の件数',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'PARENT_JOB_INTERVIEW_COUNT',
    label: '親求人 (面接あり)',
    description: '期間内作成の面接必須親求人数',
    unit: '件',
    available: true,
    calculation: 'Job.created_at が期間内 AND status="PUBLISHED" AND requires_interview=true の件数',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'PARENT_JOBS_PER_FACILITY',
    label: '施設あたり親求人数',
    description: 'マッチング応募で関わった施設 1 つあたりの親求人数 (期間内)',
    unit: '件/施設',
    available: true,
    calculation: 'PARENT_JOB_COUNT / (期間内 Application に紐付くユニーク facility_id 数)',
    supportedGroupBy: ['none'],
  },
  {
    key: 'CHILD_JOB_INTERVIEW_COUNT',
    label: '子求人 (面接あり)',
    description: '期間内作成の子求人 (JobWorkDate) のうち、紐付く親求人が面接必須のもの',
    unit: '件',
    available: true,
    calculation: 'JobWorkDate.created_at が期間内 AND job.requires_interview=true',
    supportedGroupBy: ['none', 'day'],
  },
  {
    key: 'CHILD_JOBS_PER_FACILITY',
    label: '施設あたり子求人数',
    description: '応募関連施設 1 つあたりの子求人数 (期間内)',
    unit: '件/施設',
    available: true,
    calculation: 'CHILD_JOB_COUNT / (期間内 Application に紐付くユニーク facility_id 数)',
    supportedGroupBy: ['none'],
  },
  // ── B群: 単位指標 (perWorker / perFacility) ──
  {
    key: 'MATCHINGS_PER_WORKER',
    label: 'ワーカー1人あたりマッチング数',
    description: 'マッチング数 / 応募ユニークワーカー数',
    unit: '件/人',
    available: true,
    calculation:
      'MATCHING_COUNT / Application(期間内).user_id distinct (= 期間内応募ワーカー数)',
    supportedGroupBy: ['none'],
  },
  {
    key: 'MATCHINGS_PER_FACILITY',
    label: '施設1施設あたりマッチング数',
    description: 'マッチング数 / 応募関連ユニーク施設数',
    unit: '件/施設',
    available: true,
    calculation:
      'MATCHING_COUNT / 期間内 Application の workDate.job.facility_id distinct 数',
    supportedGroupBy: ['none'],
  },
  {
    key: 'REVIEWS_PER_WORKER',
    label: 'ワーカー1人あたり受領レビュー数',
    description: '期間内に施設→ワーカーで投稿されたレビュー数 / 期間内応募ユニークワーカー数',
    unit: '件/人',
    available: true,
    calculation:
      'Review(reviewer_type=FACILITY, 期間内) の件数 / Application(期間内).user_id distinct',
    supportedGroupBy: ['none'],
  },
  {
    key: 'REVIEWS_PER_FACILITY',
    label: '施設1施設あたり受領レビュー数',
    description: '期間内ワーカー→施設レビュー数 / 期間内応募関連施設数',
    unit: '件/施設',
    available: true,
    calculation:
      'Review(reviewer_type=WORKER, 期間内) の件数 / Application(期間内) の workDate.job.facility_id distinct',
    supportedGroupBy: ['none'],
  },
  // ── B群: LP 帰属系メトリクス (lp-tracking 由来) ──
  {
    key: 'PARENT_JOB_PV',
    label: 'LP帰属 親求人 PV',
    description: 'LP 経由登録ワーカーの JobDetailPageView 総 PV',
    unit: 'PV',
    available: true,
    calculation:
      'User.registration_lp_id != null の user_id で JobDetailPageView (期間内 = created_at が期間内) の count',
    supportedGroupBy: ['none', 'lp_id'],
  },
  {
    key: 'PARENT_JOB_SESSIONS',
    label: 'LP帰属 親求人 セッション (UU)',
    description: 'LP 経由登録ワーカーで JobDetailPageView を踏んだユニークユーザー数',
    unit: 'UU',
    available: true,
    calculation:
      'User.registration_lp_id != null の user_id で JobDetailPageView (期間内) の user_id distinct',
    supportedGroupBy: ['none', 'lp_id'],
  },
  {
    key: 'LP_APPLICATION_COUNT',
    label: 'LP帰属 応募数',
    description: 'LP 経由登録ワーカーの期間内応募件数',
    unit: '件',
    available: true,
    calculation:
      'User.registration_lp_id != null の user_id で Application (期間内) の count',
    supportedGroupBy: ['none', 'lp_id'],
  },
  {
    key: 'LP_JOB_DETAIL_PV',
    label: 'LP帰属 求人詳細 PV (旧称)',
    description: 'PARENT_JOB_PV と同義 (UI 互換キー)。LP 経由登録ワーカーの JobDetailPageView 総 PV',
    unit: 'PV',
    available: true,
    calculation: 'PARENT_JOB_PV と同じロジック',
    supportedGroupBy: ['none', 'lp_id'],
  },
  {
    key: 'LP_AVG_DWELL_TIME',
    label: 'LP 平均滞在時間',
    description: 'LpEngagementSummary.total_dwell_time の平均 (秒)',
    unit: '秒',
    available: true,
    calculation:
      'LpEngagementSummary の total_dwell_time 平均。期間フィルタは created_at で適用',
    supportedGroupBy: ['none', 'lp_id'],
  },
  // ── B群: 限定求人 / 連続低評価 / 離脱率 ──
  {
    key: 'LIMITED_JOB_APPLICATION_RATE',
    label: '限定求人 応募率',
    description: '限定求人 (LIMITED_WORKED / LIMITED_FAVORITE) への応募数 / 限定求人数 × 100',
    unit: '%',
    available: true,
    calculation:
      'job.job_type IN (LIMITED_WORKED, LIMITED_FAVORITE) の Application (期間内) の件数 / LIMITED_JOB_COUNT × 100',
    supportedGroupBy: ['none'],
  },
  {
    key: 'CONSECUTIVE_LOW_RATING_WORKER_COUNT',
    label: '連続低評価ワーカー数',
    description: '直近 3 件のレビュー (reviewer_type=FACILITY) がすべて rating <= 2 のワーカー数',
    unit: '人',
    available: true,
    calculation:
      'Review (reviewer_type=FACILITY) を user_id 単位で created_at desc に並べた最初 3 件すべてが rating <= 2 のユーザー数 (期間フィルタは「最新レビュー作成日」を期間内とする)',
    supportedGroupBy: ['none'],
  },
  {
    key: 'WORKER_DROPOUT_RATE',
    label: 'ワーカー登録離脱率',
    description: '期間内登録ワーカーのうち、初応募に至らず期間末まで応募ゼロの割合 (%)',
    unit: '%',
    available: true,
    calculation:
      '期間内登録ユーザーで Application が 0 件のもの / 期間内登録ユーザー総数 × 100',
    supportedGroupBy: ['none'],
  },
  // ── D群: Attendance 系 (新規実装) ──
  {
    key: 'ATTENDANCE_CHECK_RATE',
    label: '出勤確認率',
    description: '確定応募 (status が SCHEDULED 以降) に対する実勤務 (Attendance) の割合 (%)',
    unit: '%',
    available: true,
    calculation:
      'Attendance (期間内) のユニーク application_id 数 / Application(期間内、status NOT IN [APPLIED, CANCELLED]) の件数 × 100',
    supportedGroupBy: ['none'],
  },
  {
    key: 'ATTENDANCE_COMPLETION_RATE',
    label: '勤務完了率',
    description: 'Attendance のうち status="CHECKED_OUT" の割合 (%)',
    unit: '%',
    available: true,
    calculation:
      'Attendance(期間内、status=CHECKED_OUT) の件数 / Attendance(期間内) の件数 × 100',
    supportedGroupBy: ['none'],
  },
  {
    key: 'EARLY_CHECKOUT_RATE',
    label: '早期退勤率',
    description: 'Attendance のうち check_out_type="MODIFICATION_REQUIRED" の割合 (%)',
    unit: '%',
    available: true,
    calculation:
      'Attendance(期間内、check_out_type="MODIFICATION_REQUIRED") / Attendance(期間内、check_out_time != null) × 100',
    supportedGroupBy: ['none'],
  },
  // ── D群: Bookmark / Message / Review 分布系 ──
  {
    key: 'BOOKMARK_REMOVAL_RATE',
    label: 'お気に入り解除率',
    description: '注: TASTAS では Bookmark を物理削除しているため、解除イベント自体が記録されない。常に 0% を返す参考指標。',
    unit: '%',
    available: true,
    calculation:
      '(Bookmark は物理削除のため解除イベント追跡不可) 期間内に作成されたが現存しない Bookmark 数 / 全 Bookmark 作成数 × 100。実装上は 0 を返す',
    supportedGroupBy: ['none'],
  },
  {
    key: 'MESSAGE_RESPONSE_TIME_AVG',
    label: 'メッセージ平均応答時間',
    description: 'スレッドで「ワーカー発 → 施設返信」または「施設発 → ワーカー返信」の平均応答時間 (時間)',
    unit: '時間',
    available: true,
    calculation:
      'Message を application_id+thread_id でグループ化し、from_user_id / from_facility_id の切り替わり時点で前のメッセージとの created_at 差を集計。期間内 created_at のメッセージのみ対象。avg を時間単位で算出',
    supportedGroupBy: ['none'],
  },
  {
    key: 'FACILITY_RATING_DISTRIBUTION',
    label: '施設評価分布 (1〜5点)',
    description: 'ワーカー→施設レビューの rating 別件数 (1〜5)',
    unit: '件',
    available: true,
    calculation:
      'Review(reviewer_type=WORKER, 期間内) を rating でグループ化して件数を返す。rows は rating ごとの行',
    supportedGroupBy: ['none'],
  },
  {
    key: 'WORKER_RATING_DISTRIBUTION',
    label: 'ワーカー評価分布 (1〜5点)',
    description: '施設→ワーカーレビューの rating 別件数 (1〜5)',
    unit: '件',
    available: true,
    calculation:
      'Review(reviewer_type=FACILITY, 期間内) を rating でグループ化して件数を返す。rows は rating ごとの行',
    supportedGroupBy: ['none'],
  },
  // ── D群: Repeat / LaborDoc 系 ──
  {
    key: 'REPEAT_WORKER_RATE',
    label: 'リピートワーカー率',
    description: '期間内に応募したワーカーのうち、同一施設に 2 回以上応募した人の割合 (%)',
    unit: '%',
    available: true,
    calculation:
      'Application(期間内) を (user_id, workDate.job.facility_id) で集計し、件数 >= 2 のユーザーをユニーク count → 期間内応募ユニークワーカー数で割って × 100',
    supportedGroupBy: ['none'],
  },
  {
    key: 'AVG_ATTENDANCE_HOURLY_WAGE',
    label: '実績時給平均',
    description: '完了済み Attendance の calculated_wage / 実勤務時間 の平均 (円)',
    unit: '円',
    available: true,
    calculation:
      'Attendance(期間内、status=CHECKED_OUT、actual_start_time/actual_end_time IS NOT NULL) で calculated_wage / ((actual_end_time - actual_start_time) - actual_break_time(分)/60) の平均',
    supportedGroupBy: ['none'],
  },
  {
    key: 'LABOR_DOC_SUBMISSION_RATE',
    label: '勤務報告書提出率',
    description: '確定応募に対する労働条件通知書 (LaborDocument) 作成率 (%)',
    unit: '%',
    available: true,
    calculation:
      'LaborDocument(期間内) の件数 / Application(期間内、status NOT IN [APPLIED, CANCELLED]) の件数 × 100',
    supportedGroupBy: ['none'],
  },
  // ── 取得不可 (将来実装) ──
  {
    key: 'LINE_FRIEND_ADDS',
    label: 'LINE友だち追加数',
    description: 'LINE 公式アカウントへの友だち追加数',
    unit: '人',
    available: false,
    reason: 'LINE Webhook (/api/line/webhook) が未実装のため取得できません',
    plannedFrom: 'Phase 1: LINE Messaging API 連携の実装後',
    calculation: '(未実装) LineFriendEvent テーブル予定',
    supportedGroupBy: ['none', 'day', 'lp_id'],
  },
  {
    key: 'SEARCH_QUERY_ENTRIES',
    label: '検索クエリ別流入',
    description: 'Google 検索からの検索クエリ別流入数',
    unit: '回',
    available: false,
    reason: 'Google Search Console API が未統合のため取得できません',
    plannedFrom: 'Phase 2: GSC API 統合の実装後',
    calculation: '(未実装) GSC API 経由',
    supportedGroupBy: ['none'],
  },
  {
    key: 'LSTEP_DELIVERIES',
    label: 'Lstep 配信数',
    description: 'Lステップから送信された配信メッセージ数',
    unit: '通',
    available: false,
    reason: 'Lstep webhook 連携が未実装のため取得できません',
    plannedFrom: 'Lstep webhook 受信機能の実装後',
    calculation: '(未実装) LstepEvent テーブル予定',
    supportedGroupBy: ['none', 'day'],
  },
];
